### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by rlke42** [f-bader/GPOReport#1]
The Repository currently has no license attached, and therefore (strictly speaking) its code cannot be used by others.

Would be nice if you could add one so your licensing intention is clear.

Thank you

[Github Docs](https://docs.github.com/de/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
[choosealicense.com](https://choosealicense.com/no-permission/)

**Comment by f-bader** [comment]
Added LICENSE. Have fun
